server:
    port: 9192

spring:
    h2:
        console:
            enabled: true
    application:
        name: ORDER-SERVICE

logging:
    file:
        name: C:/Users/hkhar/Desktop/logs/microservice.log