spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - AuthenticationFilter
          # filters:
          #   - name: CircuitBreaker
          #     args:
          #       name: order-service
          #       fallbackuri: forward:/orderFallBack
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - AuthenticationFilter
          # filters:
          #   - name: CircuitBreaker
          #     args:
          #       name: payment-service
          #       fallbackuri: forward:/paymentFallback
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**
                

server:
  port: 8080


#Expose all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  
